name:                miso-spa
version:             0.1

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/githubuser/miso-spa#readme>

dependencies:
- base
- bytestring
- jsaddle
- jsaddle-warp
- http-types
- miso
- text
- unordered-containers
- aeson
- network-uri
- exceptions

when:
- condition: impl(ghcjs)
  then:
    dependencies: []
  else:
    dependencies:
    - swagger2
    - wai
    - warp
    - wai-middleware-static
    - websockets
  

default-extensions:
- OverloadedStrings
- LambdaCase

library:
  source-dirs: src
